// USERS
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_DISABLED_USERS = "GET_ALL_DISABLED_USERS";
export const GET_ALL_EXISTING_USERS = "GET_ALL_EXISTING_USERS";
export const GET_USER_BY_ID= "GET_USER_BY_ID"
export const SORT_USER_BY_ID= "SORT_USER_BY_ID"
export const SORT_USER_BY_PLAN= "SORT_USER_BY_PLAN"
export const SORT_USER_BY_STATUS= "SORT_USER_BY_STATUS"
export const CREATE_USER = "CREATE_USER";
export const UPDATE_USER = "UPDATE_USER";
export const DELETE_USER = "DELETE_USER";
export const RESTORE_USER = "RESTORE_USER";
export const RESET_USERS_FILTER = "RESET_USERS_FILTER";
export const USER_DATA = "USER_DATA"
export const UPDATE_USER_DATA = "UPDATE_USER_DATA"
export const SET_FCMTOKEN_USERDATA ="SET_FCMTOKEN_USERDATA"

// STORES
export const GET_STORES = "GET_STORES"
export const GET_USER_STORE = "GET_USER_STORE"
export const DELETE_STORE = "DELETE_STORE"
export const SELECTED_STORE = "SELECTED_STORE"

// POSTS
export const GET_STORE_POSTS = "GET_STORE_POSTS"
export const UPDATE_STOCK = "UPDATE_STOCK"
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const GET_ALL_DISABLED_POSTS = "GET_ALL_DISABLED_POSTS";
export const GET_ALL_EXISTING_POSTS = "GET_ALL_EXISTING_POSTS";
export const GET_POST_BY_ID = "GET_POST_BY_ID"
export const SORT_POSTS_BY_ID= "SORT_POSTS_BY_ID"
export const SORT_POSTS_BY_STATUS= "SORT_POSTS_BY_STATUS"
export const RESET_POSTS_FILTER = "RESET_POSTS_FILTER";
export const CREATE_POST = "CREATE_POST"
export const CLEAR_DETAIL = "CLEAR_DETAIL"
export const UPDATE_POST = "UPDATE_POST"
export const DELETE_POST = "DELETE_POST"
export const RESTORE_POST = "RESTORE_POST"
export const SELECTED_POST = "SELECTED_POST"

// FAVORITES
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE"
export const GET_FAVORITES = "GET_FAVORITES"
export const ADD_FAVORITE_POST = "ADD_FAVORITE_POST";
export const REMOVE_FAVORITE_POST = "REMOVE_FAVORITE_POST"

// FILTERS
export const SELECTED_CATEGORY = "SELECTED_CATEGORY"
export const SELECTED_PRICE = "SELECTED_PRICE";
export const SELECTED_ALPHABET = "SELECTED_ALPHABET";
export const GET_STORES_BY_CATEGORY = "GET_STORES_BY_CATEGORY"
export const RESET_FILTERS = "RESET_FILTERS"

// SEARCHBAR
export const GET_STORE_BY_NAME = "GET_STORE_BY_NAME"
export const FILTER_BY_NAME = "FILTER_BY_NAME"
export const GET_POST_BY_NAME = "GET_POST_BY_NAME"

// NOTIFICATIONS
export const GET_USER_NOTIFICATIONS = "GET_USER_NOTIFICATIONS"
export const DELETE_USER_NOTIFICATIONS = "DELETE_USER_NOTIFICATIONS"
export const MARK_NOTI_AS_READ = "MARK_NOTI_AS_READ"

export const OTHER_USER_DATA = "OTHER_USER_DATA"
